#!/usr/bin/python3
import sys

def main():
        print(sys.argv)

        var=(len(sys.argv[1]))
        print('the length of first argument is :',var)
        #print(len(sys.argv[1]))
if __name__ == '__main__':
        main()
